[zd_rayleigh]
value = 40000.0
type = "float"

[zd_viscous]
value = 40000.0
type = "float"

[alpha_rayleigh_sgs_tracer]
value = 1e-3
type = "float"

[EDMF_surface_area]
value = 0.1
type = "float"

[min_area_limiter_scale]
value = 0
type = "float"

[max_area_limiter_scale]
value = 0
type = "float"

[EDMF_min_area]
value = 1.0e-5
type = "float"

[EDMF_max_area]
value = 0.7
type = "float"

[entr_inv_tau]
value = 0.0001
type = "float"

[entr_coeff]
value = 0.1
type = "float"

[detr_inv_tau]
value = 0.0001
type = "float"

[detr_coeff]
value = 0
type = "float"

[detr_buoy_coeff]
value = 1
type = "float"

[detr_vertdiv_coeff]
value = 1
type = "float"

[detr_massflux_vertdiv_coeff]
value = 0
type = "float"

[entr_detr_limit_inv_tau]
value = 0.01
type = "float"

[precipitation_timescale]
value = 1200
type = "float"

[mixing_length_eddy_viscosity_coefficient]
value = 0.56
type = "float"

[mixing_length_diss_coeff]
value = 0.22
type = "float"

[min_area_limiter_power]
value = 1
type = "float"

[max_area_limiter_power]
value = 1
type = "float"

[tracer_hyperdiffusion_factor]
value = 10

[D_horizontal_diffusion]
value = 1e6
