agents:
  queue: new-central
  slurm_time: 24:00:00
  modules: climacommon/2025_05_15

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100
  SLURM_KILL_BAD_EXIT: 1
  CONFIG_PATH: "config/longrun_configs"

timeout_in_minutes: 1440 # 24 hours

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add(\"MPI\")'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - label: "init clima :computer:"
    key: "init_cpu_env_clima"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add(\"MPI\")'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.status()'"

    agents:
      queue: clima
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Coupler integration and conservation tests"

    steps:
      - label: "Aquaplanet: evolving slab ocean"
        key: "slabplanet_aqua_evolve_ocean"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/slabplanet_aqua_evolve_ocean.yml --job_id slabplanet_aqua_evolve_ocean"
        artifact_paths: "experiments/ClimaEarth/output/slabplanet_aqua_evolve_ocean/artifacts/*"
        agents:
          slurm_mem: 32GB

      - label: "Slabplanet: fixed ocean T, bucket"
        key: "slabplanet_fixed_ocean"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/slabplanet_fixed_ocean.yml --job_id slabplanet_fixed_ocean"
        artifact_paths: "experiments/ClimaEarth/output/slabplanet_fixed_ocean/artifacts/*"
        agents:
          slurm_mem: 32GB

      - label: "Slabplanet: evolving slab ocean, bucket"
        key: "slabplanet_evolve_ocean"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/slabplanet_evolve_ocean.yml --job_id slabplanet_evolve_ocean"
        artifact_paths: "experiments/ClimaEarth/output/slabplanet_evolve_ocean/artifacts/*"
        agents:
          slurm_mem: 32GB

      - label: "GPU Aquaplanet: ED only atmosphere + slab ocean"
        key: "aquaplanet_edonly"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/aquaplanet_edonly.yml --job_id aquaplanet_edonly"
        artifact_paths: "experiments/ClimaEarth/output/aquaplanet_edonly/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          CLIMACOMMS_CONTEXT: "SINGLETON"
        agents:
          queue: clima
          slurm_mem: 32GB
          slurm_gpus: 1

      - label: "GPU Aquaplanet: diag. EDMF atmosphere + slab ocean"
        key: "aquaplanet_diagedmf"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/aquaplanet_diagedmf.yml --job_id aquaplanet_diagedmf"
        artifact_paths: "experiments/ClimaEarth/output/aquaplanet_diagedmf/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          CLIMACOMMS_CONTEXT: "SINGLETON"
        agents:
          queue: clima
          slurm_mem: 32GB
          slurm_gpus: 1
        timeout_in_minutes: 2160 # 36 hours

  - group: "AMIP simulations"

    steps:
      - label: "GPU AMIP + DecayWithHeight diffusion"
        key: "amip_decaywithheight_gpu"
        command: "srun julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_decaywithheight.yml --job_id amip_decaywithheight_gpu"
        artifact_paths: "experiments/ClimaEarth/output/amip_decaywithheight_gpu/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          queue: clima
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 32GB

      - label: "GPU AMIP + DecayWithHeight diffusion + integrated land"
        key: "amip_decaywithheight_integrated_land_gpu"
        command: "srun julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_decaywithheight_integrated_land.yml --job_id amip_decaywithheight_integrated_land_gpu"
        artifact_paths: "experiments/ClimaEarth/output/amip_decaywithheight_integrated_land_gpu/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          queue: clima
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 32GB

      - label: "GPU AMIP + ED only"
        key: "amip_edonly_gpu"
        command: "srun julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_edonly.yml --job_id amip_edonly_gpu"
        artifact_paths: "experiments/ClimaEarth/output/amip_edonly_gpu/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          queue: clima
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 32GB

      - label: "GPU AMIP + ED only + 1M microphysics"
        key: "amip_edonly_1M_gpu"
        command: "srun julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_edonly_1M.yml --job_id amip_edonly_1M_gpu"
        artifact_paths: "experiments/ClimaEarth/output/amip_edonly_1M_gpu/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          queue: clima
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 32GB

      - label: "GPU AMIP + ED only + Earth topography"
        key: "amip_edonly_topo_gpu"
        command: "srun julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_edonly_topo.yml --job_id amip_edonly_topo_gpu"
        artifact_paths: "experiments/ClimaEarth/output/amip_edonly_topo_gpu/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          queue: clima
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 32GB

      - label: "GPU AMIP + ED only + Earth topography + integrated land"
        key: "amip_edonly_topo_integrated_land_gpu" # runs for 4 months only because of instability after that time
        command: "srun julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_edonly_topo_integrated_land.yml --job_id amip_edonly_topo_integrated_land_gpu"
        artifact_paths: "experiments/ClimaEarth/output/amip_edonly_topo_integrated_land_gpu/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          queue: clima
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 32GB

      - label: "GPU AMIP + diag. EDMF + Earth topography"
        key: "amip_diagedmf_topo_gpu"
        command:
          - "srun --cpu-bind=threads --cpus-per-task=4 julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_diagedmf_topo.yml --job_id amip_diagedmf_topo_gpu"
        artifact_paths: "experiments/ClimaEarth/output/amip_diagedmf_topo_gpu/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          queue: clima
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 32GB

      - label: "GPU AMIP + diag. EDMF + Earth topography + integrated land"
        key: "amip_diagedmf_topo_integrated_land_gpu" # runs for 2 months only because of instability after that time
        command:
          - "srun --cpu-bind=threads --cpus-per-task=4 julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_diagedmf_topo_integrated_land.yml --job_id amip_diagedmf_topo_integrated_land_gpu"
        artifact_paths: "experiments/ClimaEarth/output/amip_diagedmf_topo_integrated_land_gpu/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          queue: clima
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 32GB

  - group: "CMIP simulations"

    steps:
      - label: "ClimaAtmos + ClimaLand + ClimaOcean + PrescribedSeaIce"
        key: "cmip_edonly_land"
        command:
            - "julia --color=yes --project=experiments/ClimaEarth experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/cmip_edonly_land.yml --job_id cmip_edonly_land"
        artifact_paths: "experiments/ClimaEarth/output/cmip_edonly_land/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          CLIMACOMMS_CONTEXT: "SINGLETON"
        agents:
          queue: clima
          slurm_mem: 32GB
          slurm_gpus: 1
          slurm_time: 12:00:00

      - label: "ClimaAtmos + Bucket + ClimaOcean + PrescribedSeaIce"
        key: "cmip_edonly_bucket"
        command:
            - "julia --color=yes --project=experiments/ClimaEarth experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/cmip_edonly_bucket.yml --job_id cmip_edonly_bucket"
        artifact_paths: "experiments/ClimaEarth/output/cmip_edonly_bucket/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          CLIMACOMMS_CONTEXT: "SINGLETON"
        agents:
          queue: clima
          slurm_mem: 32GB
          slurm_gpus: 1
          slurm_time: 12:00:00

  - group: "Calibration experiments"

    steps:
      - label: "Perfect model calibration test"
        key: "amip_pm_calibration"
        command:
          - "julia --color=yes --project=experiments/ClimaEarth experiments/calibration/run_calibration.jl"
        artifact_paths: "experiments/calibration/output/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          CLIMACOMMS_CONTEXT: "SINGLETON"
        agents:
          queue: clima
          slurm_mem: 96GB
          slurm_ntasks: 3
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_time: 05:00:00

  - wait

  - group: "Job analysis and reporting"

    steps:

      # plot job performance history
      - label: ":chart_with_downwards_trend: build history"
        command:
          - build_history main # name of branch to plot
        artifact_paths:
          - "build_history.html"

      - wait

      - label: ":envelope: Slack report: Slabplanet"
        command:
          - slack-upload -c "#coupler-report" -f experiments/ClimaEarth/output/slabplanet_evolve_ocean/artifacts/total_energy_bucket.png -m png -n slab_coarse -x "Slabplanet energy conservation"
          - slack-upload -c "#coupler-report" -f experiments/ClimaEarth/output/slabplanet_evolve_ocean/artifacts/total_water_bucket.png -m png -n slab_coarse_w -x "Slabplanet water conservation"
