agents:
  queue: new-central
  slurm_time: 24:00:00
  modules: climacommon/2025_05_15

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100
  SLURM_KILL_BAD_EXIT: 1
  CONFIG_PATH: "config/longrun_configs"

timeout_in_minutes: 1440 # 24 hours

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add(\"MPI\")'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - label: "init clima :computer:"
    key: "init_cpu_env_clima"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add(\"MPI\")'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.status()'"

    agents:
      queue: clima
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "AMIP simulations"

      - label: "GPU AMIP + ED only + Earth topography + integrated land"
        key: "amip_edonly_topo_integrated_land_gpu" # runs for 4 months only because of instability after that time
        command: "srun julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_edonly_topo_integrated_land.yml --job_id amip_edonly_topo_integrated_land_gpu"
        artifact_paths: "experiments/ClimaEarth/output/amip_edonly_topo_integrated_land_gpu/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          queue: clima
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 32GB

      - label: "GPU AMIP + diag. EDMF + Earth topography + integrated land"
        key: "amip_diagedmf_topo_integrated_land_gpu" # runs for 2 months only because of instability after that time
        command:
          - "srun --cpu-bind=threads --cpus-per-task=4 julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_diagedmf_topo_integrated_land.yml --job_id amip_diagedmf_topo_integrated_land_gpu"
        artifact_paths: "experiments/ClimaEarth/output/amip_diagedmf_topo_integrated_land_gpu/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          queue: clima
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 32GB
