FLOAT_TYPE: "Float32"
aerosol_radiation: true
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_allsky_0M.yml"
co2: "maunaloa"
dt: "120secs"
dt_cloud_fraction: "1hours"
dt_cpl: "120secs"
dt_rad: "1hours"
dt_save_state_to_disk: "20days"
energy_check: false
insolation: "timevarying"
land_albedo_type: "map_temporal"
mode_name: "amip"
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
prescribe_ozone: true
rad: "allskywithclear"
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "366days"
turb_flux_partition: "PartitionedStateFluxes"
