FLOAT_TYPE: "Float32"
aerosol_radiation: true
deep_atmosphere: false
mesh_warp_type: "Linear"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_allsky_0M.yml"
co2_model: "maunaloa"
dt: "120secs"
dt_cloud_fraction: "1hours"
dt_cpl: "120secs"
dt_rad: "1hours"
dt_save_state_to_disk: "20days"
energy_check: false
insolation: "timevarying"
bucket_albedo_type: "map_temporal"
mode_name: "amip"
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
prescribe_ozone: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "100days"
