FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_progedmf.yml"
checkpoint_dt: "2hours"
coupler_toml: ["toml/amip_progedmf_1m.toml"]
dt: "120secs"
dt_cpl: "120secs"
energy_check: false
implicit_microphysics: false
land_model: "integrated"
microphysics_model: "1M"
mode_name: "amip"
netcdf_output_at_levels: true
ode_algo: "ARS222"
output_default_diagnostics: true
radiation_reset_rng_seed: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "4days"
topo_smoothing: true
topography: "Earth"
use_sgs_quadrature: false
restart_dir: "/scratch/clima/slurm-buildkite/climacoupler-longruns/1081/climacoupler-longruns/output/amip_progedmf_1m_land/checkpoints/"
restart_t: "302400"
extra_atmos_diagnostics:
 - short_name: [ta, rhoa, ua, va, wa, hur, hus, cl, clw, cli, husra, hussn, pfull]
   period: 1800secs
 - short_name: [hus_neg_frac, hus_neg_mean, hus_neg_sum, hus_min]
   period: 1800secs
 - short_name: [clw_neg_frac, clw_neg_mean, clw_neg_sum, clw_min]
   period: 1800secs
 - short_name: [cli_neg_frac, cli_neg_mean, cli_neg_sum, cli_min]
   period: 1800secs
 - short_name: [husra_neg_frac, husra_neg_mean, husra_neg_sum, husra_min]
   period: 1800secs
 - short_name: [hussn_neg_frac, hussn_neg_mean, hussn_neg_sum, hussn_min]
   period: 1800secs
 - short_name: [hus_pos_frac, hus_pos_mean, hus_pos_sum, hus_max]
   period: 1800secs
 - short_name: [clw_pos_frac, clw_pos_mean, clw_pos_sum, clw_max]
   period: 1800secs
 - short_name: [cli_pos_frac, cli_pos_mean, cli_pos_sum, cli_max]
   period: 1800secs
 - short_name: [husra_pos_frac, husra_pos_mean, husra_pos_sum, husra_max]
   period: 1800secs
 - short_name: [hussn_pos_frac, hussn_pos_mean, hussn_pos_sum, hussn_max]
   period: 1800secs
 - short_name: [arup, waup, taup, thetaaup, haup, husup, hurup, clwup, cliup, waen, taen, thetaaen, haen, husen, huren, clwen, clien, tke]
   period: 1800secs
