FLOAT_TYPE: "Float32"
aerosol_radiation: true
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_allsky_0M_earth.yml"
co2_model: "maunaloa"
dt_atmos: "60secs"
dt_land: "120secs"
dt_ocean: "120secs"
dt_seaice: "120secs"
dt_cloud_fraction: "1hours"
dt_cpl: "120secs"
dt_rad: "1hours"
dt_save_state_to_disk: "20days"
energy_check: false
insolation: "timevarying"
land_model: "integrated"
mode_name: "amip"
netcdf_interpolate_z_over_msl: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
prescribe_ozone: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "732days"
topo_smoothing: true
topography: "Earth"
