aerosol_radiation: true
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_dyamond.yml"
bucket_albedo_type: "map_temporal"
dt: "30secs"
dt_cpl: "30secs"
energy_check: false
mode_name: "amip"
monthly_checkpoint: false
prescribe_ozone: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
start_date: "20100101"
t_end: "1days"
