aerosol_radiation: true
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_dyamond.yml"
dt: "30secs"
dt_cpl: "30secs"
dt_save_state_to_disk: "0.5days"
dt_save_to_sol: "0.5days"
energy_check: false
bucket_albedo_type: "map_temporal"
mode_name: "amip"
monthly_checkpoint: false
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
prescribe_ozone: true
start_date: "20100101"
t_end: "1days"
