conservation_softfail: true
dt: "200secs"
dt_cpl: "200secs"
dt_save_to_sol: "10days"
energy_check: true
evolving_ocean: false
h_elem: 6
land_albedo_type: "function"
mode_name: "slabplanet_aqua"
moist: "equil"
precip_model: "0M"
rad: "gray"
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "20days"
use_land_diagnostics: false
vert_diff: "DecayWithHeightDiffusion"
