atmos_config_file: "config/atmos_configs/climaatmos_edonly.yml"
bucket_albedo_type: "function"
dt: "240secs"
dt_cloud_fraction: "1hours"
dt_cpl: "240secs"
dt_rad: "1hours"
energy_check: true
evolving_ocean: false
h_elem: 8
mode_name: "slabplanet"
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "10days"
