atmos_config_file: "config/longrun_configs/amip_target_edonly.yml"
bucket_albedo_type: "function"
dt: "120secs"
dt_cloud_fraction: "1hours"
dt_cpl: "120secs"
dt_rad: "1hours"
energy_check: true
evolving_ocean: true
h_elem: 8
mode_name: "slabplanet"
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "90days"
