agents:
  queue: new-central
  slurm_time: 4:00:00
  modules: climacommon/2025_05_15

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/cpu"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100
  SLURM_KILL_BAD_EXIT: 1
  CONFIG_PATH: "config/ci_configs"

timeout_in_minutes: 240

steps:
  - label: "init environment :computer:"
    key: "init_cpu_env"
    command:
      - |
        if [ -n "$$CLEAR_DEPOT" ]; then
          echo "--- Clearing depot"
          rm -rf ${JULIA_DEPOT_PATH}
        fi

      - echo "--- Instantiate package env"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate ClimaEarth experiments env"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add(\"MPI\")'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate ClimaCore experiments env"
      - "julia --project=experiments/ClimaCore/ -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=experiments/ClimaCore/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/ClimaCore/ -e 'using Pkg; Pkg.add(\"MPI\")'"
      - "julia --project=experiments/ClimaCore/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/ClimaCore/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate test env"
      - "julia --project=test/ -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=test/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test/ -e 'using Pkg; Pkg.add(\"MPI\")'"
      - "julia --project=test/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=test/ -e 'using Pkg; Pkg.status()'"

    concurrency: 1
    concurrency_group: 'depot/climacoupler-ci'
    agents:
      slurm_cpus_per_task: 12
      slurm_gpus: 1
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 12
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Calibration experiments"
    steps:
      - label: "Perfect model calibration test"
        key: "amip_pm_calibration"
        command:
          - "julia --color=yes --project=experiments/ClimaEarth experiments/calibration/run_calibration.jl"
        artifact_paths: "experiments/calibration/output/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          CLIMACOMMS_CONTEXT: "SINGLETON"
          SHORT_RUN: ""
        agents:
          slurm_mem: 64GB
          slurm_ntasks: 3
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4

  - wait

  # plot job performance history
  - label: ":chart_with_downwards_trend: build history"
    command:
      - build_history staging # name of branch to plot
    artifact_paths:
      - "build_history.html"
