agents:
  queue: new-central
  slurm_time: 4:00:00
  modules: climacommon/2024_12_16

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/cpu"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100
  SLURM_KILL_BAD_EXIT: 1

  CONFIG_PATH: "config/ci_configs"

timeout_in_minutes: 240

steps:
  - label: "init environment :computer:"
    key: "init_cpu_env"
    command:
      - |
        if [ -n "$$CLEAR_DEPOT" ]; then
          echo "--- Clearing depot"
          rm -rf ${JULIA_DEPOT_PATH}
        fi

      - echo "--- Instantiate package env"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate ClimaCore experiments env"
      - "julia --project=experiments/ClimaCore/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/ClimaCore/ -e 'using Pkg; Pkg.add(\"MPI\"); Pkg.add(\"CUDA\")'"
      - "julia --project=experiments/ClimaCore/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/ClimaCore/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate ClimaEarth experiments env"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add(\"MPI\"); Pkg.add(\"CUDA\");'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate test env"
      - "julia --project=test/ -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=test/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test/ -e 'using Pkg; Pkg.add(\"MPI\"); Pkg.add(\"CUDA\")'"
      - "julia --project=test/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=test/ -e 'using Pkg; Pkg.status()'"

    concurrency: 1
    concurrency_group: 'depot/climacoupler-ci'
    agents:
      slurm_cpus_per_task: 12
      slurm_gpus: 1
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 12
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Unit Tests"
    steps:

      - label: "MPI Checkpointer unit tests"
        key: "checkpointer_mpi_tests"
        command: "srun julia --color=yes --project=test/ test/mpi_tests/checkpointer_mpi_tests.jl"
        timeout_in_minutes: 20
        env:
          CLIMACOMMS_CONTEXT: "MPI"
        agents:
          slurm_ntasks: 2
          slurm_mem: 16GB

      - label: "MPI Utilities unit tests"
        key: "utilities_mpi_tests"
        command: "srun julia --color=yes --project=test/ test/utilities_tests.jl"
        timeout_in_minutes: 20
        env:
          CLIMACOMMS_CONTEXT: "MPI"
        agents:
          slurm_ntasks: 2
          slurm_mem: 16GB

  - group: "GPU: unit tests and global bucket"
    steps:
      - label: "GPU runtests"
        command: "julia --color=yes --project=test/ test/runtests.jl"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_ntasks: 1
          slurm_gres: "gpu:1"

  - group: "Integration Tests"
    steps:
      # SLABPLANET EXPERIMENTS

      # Slabplanet default:
      # - this is the most lightweight example with conservation and visual checks, with CLI specification as follows
      #   - numerics: dt = dt_cpl = 200s, nelem = 4
      #   - physics: bulk aerodynamic surface fluxes, gray radiation, idealized insolation, equil moisture model, 0-moment microphysics
      #   - input data: monotonous remapping (land mask, SST, SIC)
      #   - slurm: unthreaded, 1 ntask
      #   - diagnostics: check and plot energy conservation, output plots after 9 days
      - label: "Slabplanet: default"
        key: "slabplanet_default"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/slabplanet_default.yml --job_id slabplanet_default"
        artifact_paths: "experiments/ClimaEarth/output/slabplanet_default/artifacts/*"
        agents:
          slurm_mem: 20GB

      - label: "Slabplanet: dry, no radiation"
        key: "slabplanet_dry_norad"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/slabplanet_dry_norad.yml --job_id slabplanet_dry_norad"
        artifact_paths: "experiments/ClimaEarth/output/slabplanet_dry_norad/artifacts/*"
        agents:
          slurm_mem: 20GB

      - label: "Slabplanet: partitioned turbulent fluxes"
        key: "slabplanet_partitioned_fluxes"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/slabplanet_partitioned_fluxes.yml --job_id slabplanet_partitioned_fluxes"
        artifact_paths: "experiments/ClimaEarth/output/slabplanet_partitioned_fluxes/artifacts/*"
        agents:
          slurm_mem: 20GB

      - label: "Slabplanet: non-monotonous surface remap"
        key: "slabplanet_nonmono"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/slabplanet_nonmono.yml --job_id slabplanet_nonmono"
        artifact_paths: "experiments/ClimaEarth/output/slabplanet_nonmono/artifacts/*"
        agents:
          slurm_mem: 20GB

      - label: "Slabplanet: eisenman sea ice"
        key: "slabplanet_eisenman"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/slabplanet_eisenman.yml --job_id slabplanet_eisenman"
        artifact_paths: "experiments/ClimaEarth/output/slabplanet_eisenman/artifacts/*"
        agents:
          slurm_mem: 20GB

      - label: "Slabplanet: extra atmos diagnostics"
        key: "slabplanet_atmos_diags"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/slabplanet_atmos_diags.yml --job_id slabplanet_atmos_diags"
        artifact_paths: "experiments/ClimaEarth/output/slabplanet_atmos_diags/artifacts/*"
        agents:
          slurm_mem: 20GB

      - label: "Slabplanet: timevarying insolation + rayleigh sponge"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/slabplanet_realinsol_rayleigh.yml --job_id slabplanet_realinsol_rayleigh"
        artifact_paths: "experiments/ClimaEarth/output/slabplanet_realinsol_rayleigh/artifacts/total_energy*.png"
        agents:
          slurm_mem: 20GB

      # AMIP EXPERIMENTS

      # Test default behavior with no config file or job ID provided
      - label: "AMIP: default"
        key: "amip_default"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl"
        artifact_paths: "experiments/ClimaEarth/output/amip_default/artifacts/*"
        agents:
          slurm_mem: 20GB

      - label: "AMIP: bucket initial condition test"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_bucket_ic.yml --job_id amip_bucket_ic"
        artifact_paths: "experiments/ClimaEarth/output/amip_bucket_ic/artifacts/*"
        agents:
          slurm_ntasks: 1
          slurm_mem: 20GB

      - label: "AMIP - Float64 + hourly checkpoint"
        key: "amip"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_coarse_ft64_hourly_checkpoints.yml --job_id amip_coarse_ft64_hourly_checkpoints"
        artifact_paths: "experiments/ClimaEarth/output/amip_coarse_ft64_hourly_checkpoints/artifacts/*"
        env:
          FLAME_PLOT: ""
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 1
          slurm_mem: 20GB

      - label: "AMIP - Float32 test"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_coarse_ft32.yml --job_id amip_coarse_ft32"
        artifact_paths: "experiments/ClimaEarth/output/amip_coarse_ft32/artifacts/*"
        agents:
          slurm_ntasks: 1
          slurm_mem: 20GB

      - label: "AMIP - Component dts test"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_component_dts.yml --job_id target_amip_component_dts"
        artifact_paths: "experiments/ClimaEarth/output/target_amip_component_dts/artifacts/*"
        agents:
          slurm_ntasks: 1
          slurm_mem: 20GB

      - label: "MPI AMIP"
        command: "srun julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_coarse_mpi.yml --job_id amip_coarse_mpi"
        artifact_paths: "experiments/ClimaEarth/output/amip_coarse_mpi/artifacts/*"
        timeout_in_minutes: 240
        env:
          CLIMACOMMS_CONTEXT: "MPI"
        agents:
          slurm_ntasks: 4
          slurm_mem: 48GB

      # short high-res performance test
      - label: "Unthreaded AMIP FINE" # also reported by longruns with a flame graph
        key: "unthreaded_amip_fine"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_n1_shortrun.yml --job_id target_amip_n1_shortrun"
        artifact_paths: "experiments/ClimaEarth/output/target_amip_n1_shortrun/artifacts/*"
        env:
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_mem: 20GB

      # CLIMACORE EXPERIMENTS

      - label: "sea_breeze"
        command: "julia --color=yes --project=experiments/ClimaCore experiments/ClimaCore/sea_breeze/run.jl"
        artifact_paths: "experiments/ClimaCore/sea_breeze/output/*"
        agents:
          slurm_mem: 20GB

      - label: "heat-diffusion"
        command: "julia --color=yes --project=experiments/ClimaCore/ experiments/ClimaCore/heat-diffusion/run.jl"
        artifact_paths: "experiments/ClimaCore/output/heat-diffusion/artifacts/*"
        agents:
          slurm_mem: 20GB

  - group: "GPU integration tests"
    steps:
      # GPU RUNS: slabplanet
      - label: "GPU Slabplanet: default"
        key: "gpu_slabplanet_default"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/slabplanet_default.yml --job_id gpu_slabplanet_default"
        artifact_paths: "experiments/ClimaEarth/output/gpu_slabplanet_default/artifacts/*"
        agents:
          slurm_mem: 20GB

      - label: "GPU Slabplanet: albedo from function"
        key: "gpu_slabplanet_albedo_function"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/slabplanet_albedo_function.yml --job_id gpu_slabplanet_albedo_function"
        artifact_paths: "experiments/ClimaEarth/output/gpu_slabplanet_albedo_function/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_mem: 20GB
          slurm_gpus: 1

      - label: "GPU Slabplanet: extra atmos diagnostics"
        key: "gpu_slabplanet_atmos_diags"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/slabplanet_atmos_diags.yml --job_id gpu_slabplanet_atmos_diags"
        artifact_paths: "experiments/ClimaEarth/output/gpu_slabplanet_atmos_diags/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_mem: 20GB
          slurm_gpus: 1

      # GPU RUNS: AMIP
      - label: "GPU AMIP: default"
        key: "gpu_amip_default"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_default.yml --job_id gpu_amip_default"
        artifact_paths: "experiments/ClimaEarth/output/gpu_amip_default/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_mem: 20GB
          slurm_gpus: 1

      - label: "GPU AMIP test: albedo from function"
        key: "gpu_amip_albedo_function"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_albedo_function.yml --job_id gpu_amip_albedo_function"
        artifact_paths: "experiments/ClimaEarth/output/gpu_amip_albedo_function/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_mem: 20GB
          slurm_gpus: 1

      - label: "GPU AMIP target: topography and diagnostic EDMF"
        key: "gpu_amip_target_topo_diagedmf_shortrun"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_target_topo_diagedmf_shortrun.yml --job_id gpu_amip_target_topo_diagedmf_shortrun"
        artifact_paths: "experiments/ClimaEarth/output/gpu_amip_target_topo_diagedmf_shortrun/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_mem: 20GB
          slurm_gpus: 1

      - label: "GPU AMIP: albedo from temporal map + 0M"
        key: "gpu_amip_albedo_temporal_map"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_albedo_temporal_map.yml --job_id gpu_amip_albedo_temporal_map"
        artifact_paths: "experiments/ClimaEarth/output/gpu_amip_albedo_temporal_map/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_mem: 20GB
          slurm_gpus: 1

      - label: "GPU AMIP: albedo from temporal map + 1M"
        key: "gpu_amip_albedo_temporal_map_1M"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_albedo_temporal_map_1M.yml --job_id gpu_amip_albedo_temporal_map_1M"
        artifact_paths: "experiments/ClimaEarth/output/gpu_amip_albedo_temporal_map_1M/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_mem: 20GB
          slurm_gpus: 1

  # - group: "Bash scripts"
  #   steps:
  #     - label: "Submit and Monitor sbatch Job on Caltech HPC"
  #       # check that (1) the script can be succesfully submitted, (2) it runs successfully
  #       command: "test/mpi_tests/test_sbatch_script.sh"
  #       agents:
  #         slurm_ntasks: 1
  #       soft_fail: true

  - group: "Hierarchy tests (1d)"
    steps:
      - label: ":construction: Dry Held Suarez"
        key: "dry_held_suarez"
        command:
          - sed 's/t_end = "1000days"/t_end = "6hours"/' experiments/ClimaEarth/run_dry_held_suarez.jl > experiments/ClimaEarth/run_dry_held_suarez_short.jl
          - "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_dry_held_suarez_short.jl"
        artifact_paths:  "dry_held_suarez/dry_held_suarez/clima_atmos/*"
        agents:
          slurm_mem: 20GB

      - label: ":construction: Moist Held Suarez"
        key: "moist_held_suarez"
        command:
          - sed 's/t_end = "1000days"/t_end = "6hours"/' experiments/ClimaEarth/run_moist_held_suarez.jl > experiments/ClimaEarth/run_moist_held_suarez_short.jl
          - "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_moist_held_suarez_short.jl"
        artifact_paths:  "moist_held_suarez/moist_held_suarez/clima_atmos/*"
        agents:
          slurm_mem: 20GB

      - label: ":construction: Cloudless Aquaplanet"
        key: "cloudless_aquaplanet"
        command:
          - sed 's/t_end = "1000days"/t_end = "6hours"/' experiments/ClimaEarth/run_cloudless_aquaplanet.jl > experiments/ClimaEarth/run_cloudless_aquaplanet_short.jl
          - "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_cloudless_aquaplanet_short.jl"
        artifact_paths:  "cloudless_aquaplanet/cloudless_aquaplanet/clima_atmos/*"
        agents:
          slurm_mem: 20GB

      - label: ":construction: Cloudy Aquaplanet"
        key: "cloudy_aquaplanet"
        command:
          - sed 's/t_end = "1000days"/t_end = "6hours"/' experiments/ClimaEarth/run_cloudy_aquaplanet.jl > experiments/ClimaEarth/run_cloudy_aquaplanet_short.jl
          - "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_cloudy_aquaplanet_short.jl"
        artifact_paths:  "cloudy_aquaplanet/cloudy_aquaplanet/clima_atmos/*"
        agents:
          slurm_mem: 20GB

      - label: ":construction: Cloudy Slabplanet"
        key: "cloudy_slabplanet"
        command:
          - sed 's/t_end = "1000days"/t_end = "6hours"/' experiments/ClimaEarth/run_cloudy_slabplanet.jl > experiments/ClimaEarth/run_cloudy_slabplanet_short.jl
          - "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_cloudy_slabplanet_short.jl"
        artifact_paths:  "cloudy_slabplanet/cloudy_slabplanet/clima_atmos/*"
        agents:
          slurm_mem: 20GB

  - wait

  # plot job performance history
  - label: ":chart_with_downwards_trend: build history"
    command:
      - build_history staging # name of branch to plot
    artifact_paths:
      - "build_history.html"

  - label: ":construction: Hierarchy plots"
    key: "hierarchy_plots"
    command:
      - "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/hierarchy/climate_plots.jl"
    artifact_paths:  "paper_figs/*"
    agents:
      slurm_mem: 20GB
