agents:
  queue: central
  slurm_time: 0:05:00

steps:
  - label: "Skip CI If we are only modifying md or .github files"
    key: "skip_ci"
    command:
      - git fetch origin main
      - git diff origin/main --name-only | grep -v ".md" | grep -v ".github" -c && exit 0 || exit 1
    soft_fail:
      - exit_status: 1
    agents:
      slurm_mem: 1GB

  - wait:
    continue_on_failure: true

  - label: "Upload pipeline"
    command: |
      if [ $$(buildkite-agent step get "outcome" --step "skip_ci") == "passed" ]; then
        buildkite-agent pipeline upload .buildkite/ci_pipeline.yml
      fi
    agents:
      slurm_mem: 1GB
