albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_wx_diagedmf.yml"
binary_area_fraction: false
checkpoint_dt: "900days"
coupler_toml: ["toml/wxquest_diagedmf.toml"]
dt_cloud_fraction: "1hours"
dt_cpl: "150secs"
dt_ogw: 1800secs
dt_rad: "1hours"
dt_seaice: "150secs"
dt: "150secs"
energy_check: false
extra_atmos_diagnostics:
  - short_name: [tas, pr, mslp, rsut, rsutcs, rlut, rlutcs, rsdt]
    period: monthly
    reduction_time: average
  - short_name: [ta, hur, pfull]
    period: monthly
    reduction_time: average
    pressure_coordinates: true
    compute_every: 6hours
FLOAT_TYPE: "Float32"
h_elem: 12
initial_condition: "WeatherModel"
lai_source: "modis_monthly_climatology"
land_fraction_source: "era5"
land_model: "integrated"
land_spun_up_ic: false
mode_name: "subseasonal"
netcdf_output_at_levels: true
non_orographic_gravity_wave: true
ode_algo: "ARS232"
output_default_diagnostics: false
radiation_reset_rng_seed: true
start_date: "20100101"
strict_params: false
surface_setup: "PrescribedSurface"
t_end: "39days"
topo_smoothing: true
topography: "Earth"
use_coupler_diagnostics: false
use_land_diagnostics: false
z_elem: 63
z_max: 60000.0
