FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_dyamond_hires.yml"
checkpoint_dt: "720hours"
co2: "maunaloa"
coupler_toml: ["toml/amip.toml"]
dt: "3secs"
dt_cpl: "3secs"
deep_atmosphere: false
dt_save_state_to_disk: "30days"
dt_save_to_sol: "30days"
dz_bottom: 30.0
energy_check: false
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
netcdf_output_at_levels: true
output_default_diagnostics: false
radiation_reset_rng_seed: true
rayleigh_sponge: true
start_date: "20160801"
surface_setup: "PrescribedSurface"
t_end: "40days"
topography: "Earth"
topo_smoothing: true
turb_flux_partition: "CombinedStateFluxesMOST"
viscous_sponge: true
h_elem: 240
z_elem: 63
z_max: 45000.0
