FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"


atmos_config_file: "config/atmos_configs/climaatmos_wx_diagedmf.yml"
# atmos_config_file: "config/atmos_configs/climaatmos_wx_progedmf.yml"

coupler_toml: ["toml/amip.toml"]
# coupler_toml: ["toml/amip_progedmf_dev.toml"]
# coupler_toml: ["toml/amip_calibrated_coarse_v1.toml"]

initial_condition: "WeatherModel"
checkpoint_dt: "93days"
co2_model: "fixed"

coupler_output_dir: "/glade/derecho/scratch/nefrathe/tmp/output_quick"

dt: "90secs"
dt_cpl: "90secs"
# dt: "5secs"
# dt_cpl: "5secs"

energy_check: false
# h_elem: 32
h_elem: 16
mode_name: "amip"

### integrated land
# land_model: "integrated"
### bucket land
land_model: "bucket"
bucket_albedo_type: "map_temporal"
# bucket_albedo_type: "map_static"

# use_land_diagnostics: true
radiation_reset_rng_seed: true
# start_date: "20250701"
start_date: "20180901"
surface_setup: "PrescribedSurface"
topo_smoothing: true
topography: "Earth"
t_end: "700days"  
netcdf_output_at_levels: true

output_default_diagnostics: false
use_coupler_diagnostics: false
use_land_diagnostics: true

extra_atmos_diagnostics:
  - short_name: [mslp, tas, pr, ta, pfull, hur, rsut, rsds, rsus, rsuscs, rsutcs, rlutcs, rlut, rlds, rlus, rlucs, ts, evspsbl, hfes]
    period: 7days
    reduction_time: average
  - short_name: [mslp, tas, pr, ta, pfull, hur, rsut, rsds, rsus, rsuscs, rsutcs, rlutcs, rlut, rlds, rlus, rlucs, ts, evspsbl, hfes]
    period: 1months
    reduction_time: average
