# grid
h_elem: 16
nh_poly: 3
z_elem: 63
z_max: 60000.0
dz_bottom: 30.0
rayleigh_sponge: true
viscous_sponge: true

# timestep
dt: "120secs"
dt_rad: "1hours"
ode_algo: ARS222
start_date: 20100101
t_end: "366days"

# parameterizations
insolation: "timevarying"
rad: "allskywithclear"
surface_setup: "DefaultMoninObukhov"
turbconv: "prognostic_edmfx"
edmfx_detr_model: "Generalized"
edmfx_entr_model: "Generalized"
microphysics_model: "1M"
cloud_model: "quadrature"
land_model: "integrated"

# parameters
coupler_toml: [toml/amip_progedmf_1m.toml]

# diagnostics
output_default_diagnostics: true
netcdf_output_at_levels: true
netcdf_interpolation_num_points: [144, 72, 63]
extra_atmos_diagnostics:
  - short_name: [hur, hus, ta]
    period: 1months
    reduction_time: average
    pressure_coordinates: true
    compute_every: 6hours
