apply_limiter: false
atmos_progress_interval: "400secs"
energy_check: false
h_elem: 4
mode_name: "amip"
rad: "allskywithclear"
microphysics_model: "0M"
share_surface_space: false
t_end: "1days"
time_varying_trace_gases: ["CO2"]
vert_diff: VerticalDiffusion
check_nan_every: 1
