FLOAT_TYPE: "Float32"
apply_limiter: false
co2_model: "maunaloa"
energy_check: false
h_elem: 6
mode_name: "amip"
moist: "equil"
precip_model: "0M"
rad: "allskywithclear"
t_end: "1days"
vert_diff: "true"
