apply_limiter: false
bucket_initial_condition: "experiments/ClimaEarth/input/bucket_ic_august.nc"
co2_model: "maunaloa"
dt: "150secs"
dt_cpl: "150secs"
dt_rad: "1hours"
dz_bottom: 30
dz_top: 3000
h_elem: 4
mode_name: "amip"
moist: "equil"
precip_model: "0M"
rad: "gray"
rayleigh_sponge: true
t_end: "300secs"
vert_diff: "true"
z_elem: 50
z_stretch: false
