FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
apply_limiter: false
atmos_config_file: "config/longrun_configs/amip_target_diagedmf.yml"
bucket_albedo_type: "map_temporal"
co2_model: "maunaloa"
dt: "100secs"
dt_cloud_fraction: "1hours"
dt_cpl: "100secs"
dt_rad: "1hours"
energy_check: false
insolation: "timevarying"
mode_name: "amip"
netcdf_output_at_levels: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "200secs"
topo_smoothing: true
topography: "Earth"
