apply_limiter: false
approximate_linear_solve_iters: 2
co2: "maunaloa"
dt: "150secs"
dt_cpl: "150secs"
dt_rad: "1hours"
dt_save_to_sol: "12hours"
dz_bottom: 30
dz_top: 3000
edmfx_sgs_diffusive_flux: true
h_elem: 4
implicit_diffusion: true
land_model: "integrated"
mode_name: "amip"
moist: "equil"
precip_model: "0M"
rad: "gray"
rayleigh_sponge: true
t_end: "31days"
turbconv: edonly_edmfx
turb_flux_partition: "PartitionedStateFluxes"
z_elem: 50
z_stretch: false
use_itime: true
