apply_limiter: false
co2: "maunaloa"
dt_save_to_sol: "1days"
energy_check: false
h_elem: 6
mode_name: "amip"
moist: "equil"
precip_model: "0M"
rad: "allskywithclear"
t_end: "10days"
vert_diff: "true"
