FLOAT_TYPE: "Float32"
apply_limiter: false
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_allsky_diagedmf_0M.yml"
co2: "maunaloa"
dt: "100secs"
dt_cloud_fraction: "1hours"
dt_cpl: "100secs"
dt_rad: "1hours"
dt_save_state_to_disk: "1days"
dt_save_to_sol: "1days"
energy_check: false
insolation: "timevarying"
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
netcdf_output_at_levels: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "200secs"
topo_smoothing: true
topography: "Earth"
turb_flux_partition: "PartitionedStateFluxes"
