anim: true
apply_limiter: false
dt: "400secs"
dt_cpl: 400
dt_save_to_sol: "1days"
energy_check: false
h_elem: 6
hourly_checkpoint: true
mode_name: "amip"
moist: "equil"
mono_surface: false
precip_model: "0M"
rad: "allskywithclear"
t_end: "10days"
vert_diff: "true"
diagnostics:
  - short_name: [mse, lr, edt, evu, ts, mass_strf, stab, vt, egr, toa_fluxes_net]
    reduction_time: average
    period: 1days
