config: "column"
domain_type: "column"
column_latlon: [37.0, -120.0]
scm_surface_type: "ocean"
mode_name: "slabplanet_aqua"
dt: "120secs"
dt_cpl: "120secs"
t_end: "480secs"
start_date: "20100101"
rad: "gray"
microphysics_model: "0M"
surface_setup: "PrescribedSurface"
vert_diff: "DecayWithHeightDiffusion"
z_elem: 30
z_max: 30000.0
z_stretch: false
