domain_type: "column"
column_latlon: [35.0, 97.0]
scm_surface_type: "land"
mode_name: "slabplanet_terra"
bucket_albedo_type: "function"
dt: "120secs"
dt_cpl: "120secs"
t_end: "480secs"
start_date: "20100101"
rad: "gray"
microphysics_model: "0M"
surface_setup: "PrescribedSurface"
vert_diff: "DecayWithHeightDiffusion"
z_elem: 30
z_max: 30000.0
z_stretch: false
