conservation_softfail: true
dt: "200secs"
dt_cpl: "200secs"
energy_check: true
h_elem: 4
bucket_albedo_type: "function"
mode_name: "slabplanet_terra"
moist: "equil"
precip_model: "0M"
rad: "gray"
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "400secs"
vert_diff: "DecayWithHeightDiffusion"
