apply_limiter: false
dt: "200secs"
dt_cpl: "200secs"
energy_check: true
h_elem: 4
mode_name: "slabplanet"
moist: "equil"
precip_model: "0M"
rad: "gray"
t_end: "1days"
vert_diff: "true"
extra_atmos_diagnostics:
  - short_name: [mse, lr, edt, evu, ts, mass_strf, stab, vt, egr, toa_fluxes_net]
    period: 1days
    reduction_time: average
