apply_limiter: false
dt: "200secs"
dt_cpl: "200secs"
dt_save_to_sol: "9days"
energy_check: true
h_elem: 4
mode_name: "slabplanet"
moist: "equil"
mono_surface: true
precip_model: "0M"
rad: "gray"
t_end: "10days"
vert_diff: "true"
extra_atmos_diagnostics:
  - short_name: [mse, lr, edt, evu, ts, mass_strf, stab, vt, egr, toa_fluxes_net]
    reduction_time: average
    period: 1days
