apply_limiter: false
dt: "200secs"
dt_cpl: "200secs"
dt_save_to_sol: "9days"
energy_check: true
h_elem: 6
mode_name: "slabplanet_eisenman"
moist: "equil"
precip_model: "0M"
rad: "gray"
surface_setup: "PrescribedSurface"
t_end: "2days"
vert_diff: "true"
