agents:
  queue: clima
  slurm_time: 14:00:00
  modules: climacommon/2025_05_15

env:
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100
  SLURM_KILL_BAD_EXIT: 1
  CONFIG_PATH: "config/nightly_configs"
  BENCHMARK_CONFIG_PATH: "config/benchmark_configs"

timeout_in_minutes: 840


steps:
  - label: "init :GPU:"
    key: "init_gpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"

      # For this pipeline, use the main branches of certain upstream packages
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add(Pkg.PackageSpec(;name=\"ClimaAtmos\", rev=\"main\"))'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add(Pkg.PackageSpec(;name=\"ClimaCore\", rev=\"main\"))'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add(Pkg.PackageSpec(;name=\"ClimaTimeSteppers\", rev=\"main\"))'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add(Pkg.PackageSpec(;name=\"Thermodynamics\", rev=\"main\"))'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add(Pkg.PackageSpec(;name=\"SurfaceFluxes\", rev=\"main\"))'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add(Pkg.PackageSpec(;name=\"RRTMGP\", rev=\"main\"))'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.resolve()'"

      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add(\"MPI\")'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Coarse AMIPs"

    steps:

      - label: "Coarse current AMIP: diagedmf + 0M + integrated land"
        key: "amip_diagedmf_land"
        command:
          - echo "--- Run simulation"
          - "julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_coarse_diagedmf_land.yml --job_id amip_coarse_diagedmf_land"
        artifact_paths: "output/amip_coarse_diagedmf_land/artifacts/*"
        timeout_in_minutes: 840
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 30GB
      
      # - label: "Coarse current AMIP: diagedmf + 1M + integrated land"
      #   key: "amip_diagedmf_1m_land"
      #   command:
      #     - echo "--- Run simulation"
      #     - "julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_coarse_diagedmf_1m_land.yml --job_id amip_coarse_diagedmf_1m_land"
      #   artifact_paths: "output/amip_coarse_diagedmf_1m_land/artifacts/*"
      #   timeout_in_minutes: 840
      #   env:
      #     CLIMACOMMS_DEVICE: "CUDA"
      #   agents:
      #     slurm_gpus_per_task: 1
      #     slurm_cpus_per_task: 4
      #     slurm_ntasks: 1
      #     slurm_mem: 30GB

      - label: "Coarse current AMIP: progedmf + 0M + bucket land"
        key: "amip_progedmf"
        command:
          - echo "--- Run simulation"
          - "julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $CONFIG_PATH/amip_coarse_progedmf.yml --job_id amip_coarse_progedmf"
        artifact_paths: "output/amip_coarse_progedmf/artifacts/*"
        timeout_in_minutes: 840
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 30GB
