agents:
  queue: clima
  slurm_time: 24:00:00
  modules: climacommon/2025_01_27

env:
  JULIA_NVTX_CALLBACKS: gc
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  SLURM_KILL_BAD_EXIT: 1
  SLURM_GRES_FLAGS: "allow-task-sharing"
  BENCHMARK_CONFIG_PATH: "config/benchmark_configs"

steps:
  - label: "init :GPU:"
    key: "init_gpu_env"
    command:
      - echo "--- Instantiate experiments/ClimaEarth"
      - julia --project=experiments/ClimaEarth -e 'using Pkg; Pkg.instantiate(;verbose=true)'
      - julia --project=experiments/ClimaEarth -e 'using Pkg; Pkg.add("MPI"); Pkg.add("CUDA")'
      - julia --project=experiments/ClimaEarth -e 'using Pkg; Pkg.precompile()'
      - julia --project=experiments/ClimaEarth -e 'using Pkg; Pkg.status()'
    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "CPU benchmarks"
    steps:
      - label: "CPU ClimaAtmos without diagnostic EDMF"
        key: "climaatmos"
        command: "srun julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/test/component_model_tests/climaatmos_standalone/atmos_driver.jl --config_file $BENCHMARK_CONFIG_PATH/climaatmos.yml --job_id climaatmos"
        artifact_paths: "experiments/ClimaEarth/output/climaatmos/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          BUILD_HISTORY_HANDLE: ""
          CLIMACOMMS_DEVICE: "CPU"
        agents:
          slurm_ntasks_per_node: 64
          slurm_nodes: 1
          slurm_mem_per_cpu: 4GB

      - label: "CPU ClimaAtmos with diagnostic EDMF"
        key: "climaatmos_diagedmf"
        command: "srun julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/test/component_model_tests/climaatmos_standalone/atmos_driver.jl --config_file $BENCHMARK_CONFIG_PATH/climaatmos_diagedmf.yml --job_id climaatmos_diagedmf"
        artifact_paths: "experiments/ClimaEarth/output/climaatmos_diagedmf/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          BUILD_HISTORY_HANDLE: ""
          CLIMACOMMS_DEVICE: "CPU"
        agents:
          slurm_ntasks_per_node: 64
          slurm_nodes: 1
          slurm_mem_per_cpu: 4GB

      - label: "CPU AMIP with diagnostic EDMF"
        key: "amip_diagedmf"
        command: "srun julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $BENCHMARK_CONFIG_PATH/amip_diagedmf.yml --job_id amip_diagedmf"
        artifact_paths: "experiments/ClimaEarth/output/amip_diagedmf/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          BUILD_HISTORY_HANDLE: ""
          CLIMACOMMS_DEVICE: "CPU"
        agents:
          slurm_ntasks_per_node: 64
          slurm_nodes: 1
          slurm_mem_per_cpu: 4GB

      - label: "CPU AMIP with diagnostic EDMF and io"
        key: "amip_diagedmf_io"
        command: "srun julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $BENCHMARK_CONFIG_PATH/amip_diagedmf_io.yml --job_id amip_diagedmf_io"
        artifact_paths: "experiments/ClimaEarth/output/amip_diagedmf_io/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          BUILD_HISTORY_HANDLE: ""
          CLIMACOMMS_DEVICE: "CPU"
        agents:
          slurm_ntasks_per_node: 64
          slurm_nodes: 1
          slurm_mem_per_cpu: 4GB

  - group: "GPU benchmarks"
    steps:
      - label: "GPU ClimaAtmos without diagnostic EDMF"
        key: "gpu_climaatmos"
        command: "srun julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/test/component_model_tests/climaatmos_standalone/atmos_driver.jl --config_file $BENCHMARK_CONFIG_PATH/climaatmos.yml --job_id gpu_climaatmos"
        artifact_paths: "experiments/ClimaEarth/output/gpu_climaatmos/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 2
          slurm_mem: 16GB

      - label: "GPU ClimaAtmos with diagnostic EDMF"
        key: "gpu_climaatmos_diagedmf"
        command: "srun julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/test/component_model_tests/climaatmos_standalone/atmos_driver.jl --config_file $BENCHMARK_CONFIG_PATH/climaatmos_diagedmf.yml --job_id gpu_climaatmos_diagedmf"
        artifact_paths: "experiments/ClimaEarth/output/gpu_climaatmos_diagedmf/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 2
          slurm_mem: 16GB

      - label: "GPU AMIP with diagnostic EDMF"
        key: "gpu_amip_diagedmf"
        command: "srun julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $BENCHMARK_CONFIG_PATH/amip_diagedmf.yml --job_id gpu_amip_diagedmf"
        artifact_paths: "experiments/ClimaEarth/output/gpu_amip_diagedmf/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 2
          slurm_mem: 16GB

      - label: "GPU AMIP with diagnostic EDMF and IO"
        key: "gpu_amip_diagedmf_io"
        command: "srun julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $BENCHMARK_CONFIG_PATH/amip_diagedmf_io.yml --job_id gpu_amip_diagedmf_io"
        artifact_paths: "experiments/ClimaEarth/output/gpu_amip_diagedmf_io/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 2
          slurm_mem: 16GB

  - group: "Generate output table"
    steps:
      - label: "Compare AMIP/Atmos-only with diagnostic EDMF"
        key: "compare_amip_climaatmos_amip_diagedmf"
        command: "julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/user_io/benchmarks.jl --cpu_job_id_coupled amip_diagedmf --cpu_job_id_coupled_io amip_diagedmf_io --cpu_job_id_atmos_diagedmf climaatmos_diagedmf --cpu_job_id_atmos climaatmos --build_id $BUILDKITE_BUILD_NUMBER"
        artifact_paths: "experiments/ClimaEarth/output/compare_amip_climaatmos_amip_diagedmf/*"
        depends_on:
          - "climaatmos"
          - "climaatmos_diagedmf"
          - "amip_diagedmf"
          - "amip_diagedmf_io"
          - "gpu_climaatmos"
          - "gpu_climaatmos_diagedmf"
          - "gpu_amip_diagedmf"
          - "gpu_amip_diagedmf_io"

      - label: ":envelope: Slack report: CPU/GPU AMIP/Atmos-only table"
        depends_on:
          - "compare_amip_climaatmos_amip_diagedmf"
        command:
          - slack-upload -c "#coupler-report" -f experiments/ClimaEarth/output/compare_amip_climaatmos_amip_diagedmf/table.txt -m txt -n compare_amip_climaatmos_amip_diagedmf_table -x "Coupler CPU/GPU Comparison Table"
