agents:
  queue: clima
  slurm_time: 24:00:00
  modules: climacommon/2025_05_15

env:
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  SLURM_KILL_BAD_EXIT: 1
  SLURM_GRES_FLAGS: "allow-task-sharing"
  BENCHMARK_CONFIG_PATH: "config/benchmark_configs"

steps:
  - label: "init :GPU:"
    key: "init_gpu_env"
    command:
      - echo "--- Instantiate experiments/ClimaEarth"
      - julia --project=experiments/ClimaEarth -e 'using Pkg; Pkg.instantiate(;verbose=true)'
      - julia --project=experiments/ClimaEarth -e 'using Pkg; Pkg.add("MPI");'
      - julia --project=experiments/ClimaEarth -e 'using Pkg; Pkg.precompile()'
      - julia --project=experiments/ClimaEarth -e 'using Pkg; Pkg.status()'
    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "GPU benchmarks for flagship amip"
    steps:
      - label: "GPU AMIP with prognostic EDMF + 1M + integrated land (16 helems)"
        key: "gpu_amip_progedmf_1M_land_he16"
        command: "srun julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $BENCHMARK_CONFIG_PATH/amip_progedmf_1m_land_he16.yml --job_id gpu_amip_progedmf_1M_land_he16"
        artifact_paths: "output/gpu_amip_progedmf_1M_land_he16/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 16GB

      - label: "GPU AMIP with prognostic EDMF + 1M + integrated land (30 helems)"
        key: "gpu_amip_progedmf_1M_land_he30"
        command: "srun julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $BENCHMARK_CONFIG_PATH/amip_progedmf_1m_land_he30.yml --job_id gpu_amip_progedmf_1M_land_he30"
        artifact_paths: "output/gpu_amip_progedmf_1M_land_he30/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 16GB

  - group: "GPU benchmarks"
    steps:
      - label: "GPU ClimaAtmos without diagnostic EDMF"
        key: "gpu_climaatmos"
        command: "srun julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/test/component_model_tests/climaatmos_standalone/atmos_driver.jl --config_file $BENCHMARK_CONFIG_PATH/climaatmos.yml --job_id gpu_climaatmos"
        artifact_paths: "output/gpu_climaatmos/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 2
          slurm_mem: 16GB

      - label: "GPU ClimaAtmos with diagnostic EDMF"
        key: "gpu_climaatmos_diagedmf"
        command: "srun julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/test/component_model_tests/climaatmos_standalone/atmos_driver.jl --config_file $BENCHMARK_CONFIG_PATH/climaatmos_diagedmf.yml --job_id gpu_climaatmos_diagedmf"
        artifact_paths: "output/gpu_climaatmos_diagedmf/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 2
          slurm_mem: 16GB

      - label: "GPU AMIP with diagnostic EDMF"
        key: "gpu_amip_diagedmf"
        command: "srun julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $BENCHMARK_CONFIG_PATH/amip_diagedmf.yml --job_id gpu_amip_diagedmf"
        artifact_paths: "output/gpu_amip_diagedmf/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 2
          slurm_mem: 16GB

      - label: "GPU AMIP with diagnostic EDMF and IO"
        key: "gpu_amip_diagedmf_io"
        command: "srun julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $BENCHMARK_CONFIG_PATH/amip_diagedmf_io.yml --job_id gpu_amip_diagedmf_io"
        artifact_paths: "output/gpu_amip_diagedmf_io/artifacts/*"
        env:
          CLIMACOMMS_CONTEXT: "MPI"
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 2
          slurm_mem: 16GB


  - group: "Generate output table"
    steps:
      - label: "Compare AMIP/Atmos-only with diagnostic EDMF"
        key: "compare_amip_climaatmos_amip_diagedmf"
        command: |
          julia --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/user_io/benchmarks.jl \
            --job_id_coupled gpu_amip_diagedmf \
            --job_id_coupled_io gpu_amip_diagedmf_io \
            --job_id_atmos_diagedmf gpu_climaatmos_diagedmf \
            --job_id_atmos gpu_climaatmos \
            --job_id_coupled_progedmf_coarse gpu_amip_progedmf_1M_land_he16 \
            --job_id_coupled_progedmf_fine gpu_amip_progedmf_1M_land_he30 \
            --build_id $BUILDKITE_BUILD_NUMBER
        artifact_paths: "output/compare_amip_climaatmos_amip_diagedmf/*"
        depends_on:
          - "gpu_climaatmos"
          - "gpu_climaatmos_diagedmf"
          - "gpu_amip_diagedmf"
          - "gpu_amip_diagedmf_io"
          - "gpu_amip_progedmf_1M_land_he16"
          - "gpu_amip_progedmf_1M_land_he30"

      - label: ":envelope: Slack report: GPU AMIP/Atmos-only table"
        depends_on:
          - "compare_amip_climaatmos_amip_diagedmf"
        command:
          - slack-upload -c C04S6MBSDC4 -f experiments/ClimaEarth/output/compare_amip_climaatmos_amip_diagedmf/table.txt -n compare_amip_climaatmos_amip_diagedmf_table -x "Coupler CPU/GPU Comparison Table"
