agents:
  queue: clima
  slurm_time: 24:00:00
  modules: climacommon/2025_05_15

env:
  JULIA_NVTX_CALLBACKS: gc
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  SLURM_KILL_BAD_EXIT: 1
  SLURM_GRES_FLAGS: "allow-task-sharing"
  BENCHMARK_CONFIG_PATH: "config/benchmark_configs"

steps:
  - label: "init :GPU:"
    key: "init_gpu_env"
    command:
      - echo "--- Instantiate experiments/ClimaEarth"
      - julia --project=experiments/ClimaEarth -e 'using Pkg; Pkg.instantiate(;verbose=true)'
      - julia --project=experiments/ClimaEarth -e 'using Pkg; Pkg.add("MPI"); Pkg.add("CUDA")'
      - julia --project=experiments/ClimaEarth -e 'using Pkg; Pkg.precompile()'
      - julia --project=experiments/ClimaEarth -e 'using Pkg; Pkg.status()'
    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "GPU benchmarks for flagship amip"
    steps:
      - label: "GPU AMIP with prognostic EDMF + 1M + integrated land (16 helems)"
        key: "gpu_amip_progedmf_1M_land_he16"
        command: "srun julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $BENCHMARK_CONFIG_PATH/amip_progedmf_1m_land_he16.yml --job_id gpu_amip_progedmf_1M_land_he16"
        artifact_paths: "experiments/ClimaEarth/output/gpu_amip_progedmf_1M_land_he16/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 16GB 

      - label: "GPU AMIP with prognostic EDMF + 1M + integrated land (30 helems)"
        key: "gpu_amip_progedmf_1M_land_he30"
        command: "srun julia --threads=3 --color=yes --project=experiments/ClimaEarth/ experiments/ClimaEarth/run_amip.jl --config_file $BENCHMARK_CONFIG_PATH/amip_progedmf_1m_land_he30.yml --job_id gpu_amip_progedmf_1M_land_he30"
        artifact_paths: "experiments/ClimaEarth/output/gpu_amip_progedmf_1M_land_he30/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 16GB
