FLOAT_TYPE: "Float32"
aerosol_radiation: true
atmos_config_file: "config/benchmark_configs/climaatmos_diagedmf.yml"
atmos_config_repo: "ClimaCoupler"
dt: "120secs"
dt_cpl: "120secs"
dt_save_state_to_disk: "Inf"
dt_save_to_sol: "Inf"
energy_check: false
land_albedo_type: "map_temporal"
mode_name: "amip"
monthly_checkpoint: false
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
prescribe_ozone: true
start_date: "20100101"
t_end: "12hours"
turb_flux_partition: "PartitionedStateFluxes"
use_coupler_diagnostics: false
