
FLOAT_TYPE: "Float32"
aerosol_radiation: true
approximate_linear_solve_iters: 2
co2_model: "maunaloa"
dt: 120secs
dt_cloud_fraction: 1hours
dt_rad: 1hours
dt_save_state_to_disk: "12hours"
dz_bottom: 30.0
dz_top: 3000.0
edmfx_detr_model: "Generalized"
edmfx_entr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_sgs_diffusive_flux: true
edmfx_sgs_mass_flux: true
edmfx_upwinding: first_order
h_elem: 30
implicit_diffusion: true
insolation: "timevarying"
moist: equil
ode_algo: ARS343
output_default_diagnostics: false
precip_model: 0M
prescribe_ozone: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
prognostic_tke: true
rad: allskywithclear
surface_setup: DefaultMoninObukhov
t_end: 12hours
toml: [toml/diagnostic_edmfx.toml]
turbconv: diagnostic_edmfx
z_elem: 63
z_max: 55000.0
extra_atmos_diagnostics:
  - short_name: [pfull, rsut, rlut, pr, hus, rv]
    period: 10hours
