agents:
  queue: gcp

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  CONFIG_PATH: "config/amip_configs"

steps:
  - label: "init :GPU:"
    key: "init_gpu_env"
    command:
      - "echo --- Instantiate AMIP env"
      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'
      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add("MPI")'
      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add("CUDA")'
      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.precompile()'
      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.status()'

    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "High-resolution AMIPs and CMIPs"

    steps:


      - label: "Current AMIP: diagedmf + 0M + bucket land"
        key: "amip"
        command:
          - echo "--- Run simulation"
          - .buildkite/gcp/run_amip_with_tmp_checkpoints.sh $CONFIG_PATH/amip.yml amip
        artifact_paths: "experiments/ClimaEarth/output/amip/artifacts/*"
        timeout_in_minutes: 7220
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 0GB
          slurm_time: "120:00:00"
      
      - label: "Current AMIP: diagedmf + 0M + integrated land"
        key: "amip_land"
        command:
          - echo "--- Run simulation"
          - .buildkite/gcp/run_amip_with_tmp_checkpoints.sh $CONFIG_PATH/amip_land.yml amip_land
        artifact_paths: "experiments/ClimaEarth/output/amip_land/artifacts/*"
        timeout_in_minutes: 7220
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 0GB
          slurm_time: "120:00:00"
