agents:
  queue: gcp

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"

steps:
  - label: "init :GPU:"
    key: "init_gpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"

      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add("MPI")'
      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add("CUDA"); using CUDA; CUDA.set_runtime_version!(local_toolkit=true)'
      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary(library_names="/sw/openmpi-5.0.5/lib/libmpi", mpiexec="/sw/openmpi-5.0.5/bin/mpiexec", force=true)'

      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.precompile()'
      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.status()'

    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "High-resolution AMIPs and CMIPs"

    steps:

      - label: "30 h_elem current AMIP: diagedmf + 0M + bucket land"
        key: "amip"
        command:

          - echo "--- Run simulation"
          - | 
            srun -n 1 julia --project=experiments/ClimaEarth -e '
            using CUDA
            A = CUDA.fill(1.0f0, 1024, 1024)
            B = similar(v)
            copy!(B, v)
            synchronize(); println("OK")
            '
        artifact_paths: "experiments/ClimaEarth/output/amip_coarse/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          CLIMACOMMS_CONTEXT: "SINGLETON"
        agents:
          slurm_gpus: 1

