agents:
  queue: gcp

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  CONFIG_PATH: "config/amip_configs"

steps:
  - label: "init :GPU:"
    key: "init_gpu_env"
    command:
      - "echo --- Instantiate AMIP env"
      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'
      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add("MPI")'
      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.add("CUDA")'
      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.precompile()'
      - julia --project=experiments/ClimaEarth/ -e 'using Pkg; Pkg.status()'

    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "High-resolution AMIPs and CMIPs"

    steps:


      - label: "Current AMIP: diagedmf + 0M + bucket land"
        key: "amip"
        command:
          - echo "--- Run simulation"
          - |
            julia --threads=3 --color=yes --project=experiments/ClimaEarth/ \
            experiments/ClimaEarth/run_amip.jl \
            --config_file $CONFIG_PATH/amip.yml \
            --job_id amip
        artifact_paths: "experiments/ClimaEarth/output/amip/artifacts/*"
        timeout_in_minutes: 5760
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 30GB
          slurm_time: "60:00:00"

      - label: "10-year 30 h_elem current AMIP: diagedmf + 0M + bucket land"
        key: "10year_amip"
        command:

          - echo "--- Run simulation"
          - |
            mpiexec -n 8 julia --threads=4 --color=yes \
                    --project=experiments/ClimaEarth/ \
                    experiments/ClimaEarth/run_amip.jl \
                    --config_file config/longrun_configs/amip_diagedmf_10years.yml \
                    --job_id amip_30_h_elem
        artifact_paths: "experiments/ClimaEarth/output/amip_coarse/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          CLIMACOMMS_CONTEXT: "MPI"
        agents:
          slurm_gpus: 8
          slurm_cpus_per_task: 4
          slurm_ntasks: 8
          slurm_mem: 0GB
          slurm_time: "144:00:00"
